name: Build on release
on:
  release:
    types: [published]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push service
        run: |
          docker buildx build \
            --file Dockerfile \  # Adjust the path to your Dockerfile if necessary
            --tag ghcr.io/coop25/meme-index-api:latest \
            --push \
            .